; generated by PrusaSlicer 2.3.0+ on 2021-05-09 at 02:27:04 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M201 X500 Y500 Z100 E5000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z10 E60 ; sets maximum feedrates, mm/sec
M204 P500 R1000 T500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E5.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S200 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S200 ; wait for extruder temp
G28 ; home all
G1 Z2 F240
G1 X2 Y10 F3000
G1 Z0.28 F240
G92 E0
G1 Y190 E15 F1500 ; intro line
G1 X2.3 F5000
G92 E0
G1 Y10 E15 F1200 ; intro line
G92 E0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;0.2


G1 E-6.50000 F3300.000
G1 Z0.200 F9000.000
;AFTER_LAYER_CHANGE
;0.2
G1 X103.534 Y112.381
G1 E6.50000 F2400.000
;TYPE:Skirt
;WIDTH:0.42
G1 F900
G1 X104.139 Y111.998 E0.02243
G1 X104.814 Y111.763 E0.02243
G1 X105.486 Y111.687 E0.02120
G1 X125.504 Y111.687 E0.62765
G1 X126.078 Y111.741 E0.01807
G1 X126.636 Y111.900 E0.01820
G1 X127.155 Y112.160 E0.01820
G1 X127.614 Y112.509 E0.01807
G1 X128.002 Y112.935 E0.01807
G1 X128.307 Y113.430 E0.01820
G1 X128.515 Y113.972 E0.01820
G1 X128.619 Y114.538 E0.01807
G1 X128.613 Y116.522 E0.06220
G1 X128.498 Y117.087 E0.01807
G1 X128.281 Y117.621 E0.01807
G1 X127.902 Y118.191 E0.02148
G1 X127.411 Y118.663 E0.02134
G1 X126.830 Y119.017 E0.02134
G1 X126.186 Y119.237 E0.02134
G1 X125.509 Y119.313 E0.02134
G1 X105.190 Y119.298 E0.63709
G1 X104.247 Y119.051 E0.03058
G1 X103.424 Y118.526 E0.03058
G1 X102.804 Y117.774 E0.03058
G1 X102.445 Y116.867 E0.03058
G1 X102.370 Y116.278 E0.01861
G1 X102.375 Y114.617 E0.05208
G1 X102.466 Y114.044 E0.01820
G1 X102.659 Y113.501 E0.01807
G1 X103.032 Y112.891 E0.02243
G1 X103.492 Y112.424 E0.02055
G1 X103.002 Y113.658 F9000.000
G1 F900
G1 X103.339 Y113.111 E0.02014
G1 X103.789 Y112.660 E0.02001
G1 X104.336 Y112.322 E0.02014
G1 X104.945 Y112.120 E0.02014
G1 X105.491 Y112.064 E0.01720
G1 X125.504 Y112.064 E0.62749
G1 X126.505 Y112.254 E0.03195
G1 X127.369 Y112.795 E0.03195
G1 X127.977 Y113.613 E0.03195
G1 X128.245 Y114.596 E0.03195
G1 X128.240 Y116.464 E0.05857
G1 X127.953 Y117.434 E0.03170
G1 X127.612 Y117.949 E0.01937
G1 X127.169 Y118.373 E0.01924
G1 X126.642 Y118.688 E0.01924
G1 X126.055 Y118.880 E0.01937
G1 X125.505 Y118.936 E0.01733
G1 X105.246 Y118.924 E0.63520
G1 X104.396 Y118.705 E0.02752
G1 X103.661 Y118.232 E0.02739
G1 X103.112 Y117.553 E0.02739
G1 X102.802 Y116.736 E0.02739
G1 X102.752 Y114.638 E0.06581
G1 X102.987 Y113.716 E0.02982
G1 X103.340 Y113.825 F9000.000
G1 F900
G1 X103.636 Y113.342 E0.01775
G1 X104.038 Y112.944 E0.01775
G1 X104.523 Y112.651 E0.01775
G1 X105.063 Y112.482 E0.01775
G1 X125.504 Y112.441 E0.64090
G1 X126.374 Y112.608 E0.02778
G1 X127.123 Y113.081 E0.02778
G1 X127.645 Y113.793 E0.02767
G1 X127.871 Y114.650 E0.02778
G1 X127.866 Y116.406 E0.05508
G1 X127.627 Y117.244 E0.02731
G1 X127.327 Y117.702 E0.01716
G1 X126.931 Y118.080 E0.01716
G1 X126.459 Y118.357 E0.01716
G1 X125.937 Y118.518 E0.01716
G1 X105.302 Y118.551 E0.64698
G1 X104.552 Y118.362 E0.02426
G1 X103.905 Y117.944 E0.02414
G1 X103.425 Y117.342 E0.02414
G1 X103.163 Y116.618 E0.02414
G1 X103.128 Y114.670 E0.06111
G1 X103.326 Y113.883 E0.02543
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X103.636 Y113.342 E-0.27157
G1 X104.038 Y112.944 E-0.24653
G1 X104.523 Y112.651 E-0.24653
G1 X105.063 Y112.482 E-0.24653
G1 X106.996 Y112.478 E-0.84133
;WIPE_END
G1 E-0.09750 F3300.000
G1 X105.810 Y115.308 F9000.000
G1 E6.50000 F2400.000
;TYPE:External perimeter
G1 F900
G1 X125.190 Y115.308 E0.60765
G1 X125.190 Y115.692 E0.01203
G1 X105.810 Y115.692 E0.60765
G1 X105.810 Y115.368 E0.01015
G1 X106.210 Y115.311 F9000.000
M106 S255
;LAYER_CHANGE
;Z:0.36
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;0.36


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X110.065 Y115.355 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z0.360 F9000.000
;AFTER_LAYER_CHANGE
;0.36
M104 S190 ; set temperature
G1 X102.804 Y117.774
G1 E6.50000 F2400.000
;TYPE:Skirt
G1 F900
G1 X102.445 Y116.867 E0.02502
G1 X102.370 Y116.278 E0.01523
G1 X102.375 Y114.617 E0.04262
G1 X102.466 Y114.044 E0.01489
G1 X102.659 Y113.501 E0.01478
G1 X103.032 Y112.891 E0.01835
G1 X103.534 Y112.381 E0.01835
G1 X104.139 Y111.998 E0.01835
G1 X104.814 Y111.763 E0.01835
G1 X105.486 Y111.687 E0.01735
G1 X125.504 Y111.687 E0.51355
G1 X126.078 Y111.741 E0.01478
G1 X126.636 Y111.900 E0.01489
G1 X127.155 Y112.160 E0.01489
G1 X127.614 Y112.509 E0.01478
G1 X128.002 Y112.935 E0.01478
G1 X128.307 Y113.430 E0.01489
G1 X128.515 Y113.972 E0.01489
G1 X128.619 Y114.538 E0.01478
G1 X128.613 Y116.522 E0.05089
G1 X128.498 Y117.087 E0.01478
G1 X128.281 Y117.621 E0.01478
G1 X127.902 Y118.191 E0.01757
G1 X127.411 Y118.663 E0.01746
G1 X126.830 Y119.017 E0.01746
G1 X126.186 Y119.237 E0.01746
G1 X125.509 Y119.313 E0.01746
G1 X105.190 Y119.298 E0.52127
G1 X104.247 Y119.051 E0.02502
G1 X103.424 Y118.526 E0.02502
G1 X102.842 Y117.820 E0.02348
G1 X102.802 Y116.736 F9000.000
G1 F900
G1 X102.752 Y114.638 E0.05385
G1 X103.002 Y113.658 E0.02594
G1 X103.339 Y113.111 E0.01648
G1 X103.789 Y112.660 E0.01637
G1 X104.336 Y112.322 E0.01648
G1 X104.945 Y112.120 E0.01648
G1 X105.491 Y112.064 E0.01407
G1 X125.504 Y112.064 E0.51342
G1 X126.505 Y112.254 E0.02614
G1 X127.369 Y112.795 E0.02614
G1 X127.977 Y113.613 E0.02614
G1 X128.245 Y114.596 E0.02614
G1 X128.240 Y116.464 E0.04792
G1 X127.953 Y117.434 E0.02594
G1 X127.612 Y117.949 E0.01585
G1 X127.169 Y118.373 E0.01574
G1 X126.642 Y118.688 E0.01574
G1 X126.055 Y118.880 E0.01585
G1 X125.505 Y118.936 E0.01418
G1 X105.246 Y118.924 E0.51972
G1 X104.396 Y118.705 E0.02252
G1 X103.661 Y118.232 E0.02241
G1 X103.112 Y117.553 E0.02241
G1 X102.823 Y116.792 E0.02087
G1 X103.180 Y116.663 F9000.000
G1 F900
G1 X103.163 Y116.618 E0.00123
G1 X103.128 Y114.670 E0.05000
G1 X103.340 Y113.825 E0.02235
G1 X103.636 Y113.342 E0.01453
G1 X104.038 Y112.944 E0.01453
G1 X104.523 Y112.651 E0.01453
G1 X105.063 Y112.482 E0.01453
G1 X125.504 Y112.441 E0.52439
G1 X126.374 Y112.608 E0.02273
G1 X127.123 Y113.081 E0.02273
G1 X127.645 Y113.793 E0.02264
G1 X127.871 Y114.650 E0.02273
G1 X127.866 Y116.406 E0.04506
G1 X127.627 Y117.244 E0.02235
G1 X127.327 Y117.702 E0.01404
G1 X126.931 Y118.080 E0.01404
G1 X126.459 Y118.357 E0.01404
G1 X125.937 Y118.518 E0.01404
G1 X105.302 Y118.551 E0.52937
G1 X104.552 Y118.362 E0.01985
G1 X103.905 Y117.944 E0.01975
G1 X103.425 Y117.342 E0.01975
G1 X103.200 Y116.720 E0.01698
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X103.163 Y116.618 E-0.04698
G1 X103.128 Y114.670 E-0.84865
G1 X103.340 Y113.825 E-0.37930
G1 X103.636 Y113.342 E-0.24653
G1 X104.038 Y112.944 E-0.24653
G1 X104.205 Y112.843 E-0.08451
;WIPE_END
G1 E-0.09750 F3300.000
G1 X106.141 Y115.541 F9000.000
G1 E6.50000 F2400.000
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X106.141 Y115.459 E0.00228
G1 X124.859 Y115.459 E0.51757
G1 X124.859 Y115.541 E0.00228
G1 X106.201 Y115.541 E0.51591
G1 X105.725 Y115.957 F9000.000
;TYPE:External perimeter
G1 F900
G1 X105.725 Y115.043 E0.02526
G1 X125.275 Y115.043 E0.54056
G1 X125.275 Y115.957 E0.02526
G1 X105.785 Y115.957 E0.53890
G1 X105.920 Y115.607 F9000.000
;LAYER_CHANGE
;Z:0.52
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;0.52


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X105.725 Y115.043 E-0.39867
G1 X109.064 Y115.043 E-1.45383
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z0.520 F9000.000
;AFTER_LAYER_CHANGE
;0.52
G1 X106.141 Y115.701
G1 E6.50000 F2400.000
;TYPE:Perimeter
G1 F900
G1 X106.141 Y115.299 E0.01112
G1 X124.859 Y115.299 E0.51757
G1 X124.859 Y115.701 E0.01112
G1 X106.201 Y115.701 E0.51591
G1 X105.725 Y116.117 F9000.000
;TYPE:External perimeter
G1 F900
G1 X105.725 Y114.883 E0.03411
G1 X125.275 Y114.883 E0.54056
G1 X125.275 Y116.117 E0.03411
G1 X105.785 Y116.117 E0.53890
G1 X105.918 Y115.766 F9000.000
;LAYER_CHANGE
;Z:0.68
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;0.68


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X105.725 Y114.883 E-0.53778
G1 X108.744 Y114.883 E-1.31472
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z0.680 F9000.000
;AFTER_LAYER_CHANGE
;0.68
G1 X106.141 Y115.171
G1 E6.50000 F2400.000
;TYPE:Perimeter
G1 F900
G1 X124.859 Y115.171 E0.51757
G1 X124.859 Y115.829 E0.01822
G1 X106.141 Y115.829 E0.51757
G1 X106.141 Y115.231 E0.01656
G1 X105.725 Y114.755 F9000.000
;TYPE:External perimeter
G1 F900
G1 X125.275 Y114.755 E0.54056
G1 X125.275 Y116.245 E0.04120
G1 X105.725 Y116.245 E0.54056
G1 X105.725 Y114.815 E0.03954
G1 X106.125 Y114.765 F9000.000
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X109.980 Y114.802 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 X124.652 Y115.500 F9000.000
G1 E6.50000 F2400.000
;TYPE:Gap fill
;WIDTH:0.277496
G1 F900
G1 X106.348 Y115.500 E0.29605
;LAYER_CHANGE
;Z:0.84
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;0.84


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X110.603 Y115.500 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z0.840 F9000.000
;AFTER_LAYER_CHANGE
;0.84
G1 X106.141 Y115.171
G1 E6.50000 F2400.000
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X124.859 Y115.171 E0.51757
G1 X124.859 Y115.829 E0.01822
G1 X106.141 Y115.829 E0.51757
G1 X106.141 Y115.231 E0.01656
G1 X105.725 Y114.755 F9000.000
;TYPE:External perimeter
G1 F900
G1 X125.275 Y114.755 E0.54056
G1 X125.275 Y116.245 E0.04120
G1 X105.725 Y116.245 E0.54056
G1 X105.725 Y114.815 E0.03954
G1 X106.125 Y114.765 F9000.000
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X109.980 Y114.802 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 X124.652 Y115.500 F9000.000
G1 E6.50000 F2400.000
;TYPE:Gap fill
;WIDTH:0.277496
G1 F900
G1 X106.348 Y115.500 E0.29605
;LAYER_CHANGE
;Z:1
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;1


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X110.603 Y115.500 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z1.000 F9000.000
;AFTER_LAYER_CHANGE
;1
G1 X106.141 Y115.171
G1 E6.50000 F2400.000
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X124.859 Y115.171 E0.51757
G1 X124.859 Y115.829 E0.01822
G1 X106.141 Y115.829 E0.51757
G1 X106.141 Y115.231 E0.01656
G1 X105.725 Y114.755 F9000.000
;TYPE:External perimeter
G1 F900
G1 X125.275 Y114.755 E0.54056
G1 X125.275 Y116.245 E0.04120
G1 X105.725 Y116.245 E0.54056
G1 X105.725 Y114.815 E0.03954
G1 X106.125 Y114.765 F9000.000
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X109.980 Y114.802 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 X124.652 Y115.500 F9000.000
G1 E6.50000 F2400.000
;TYPE:Gap fill
;WIDTH:0.277496
G1 F900
G1 X106.348 Y115.500 E0.29605
;LAYER_CHANGE
;Z:1.16
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;1.16


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X110.603 Y115.500 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z1.160 F9000.000
;AFTER_LAYER_CHANGE
;1.16
G1 X106.141 Y115.171
G1 E6.50000 F2400.000
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X124.859 Y115.171 E0.51757
G1 X124.859 Y115.829 E0.01822
G1 X106.141 Y115.829 E0.51757
G1 X106.141 Y115.231 E0.01656
G1 X105.725 Y114.755 F9000.000
;TYPE:External perimeter
G1 F900
G1 X125.275 Y114.755 E0.54056
G1 X125.275 Y116.245 E0.04120
G1 X105.725 Y116.245 E0.54056
G1 X105.725 Y114.815 E0.03954
G1 X106.125 Y114.765 F9000.000
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X109.980 Y114.802 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 X124.652 Y115.500 F9000.000
G1 E6.50000 F2400.000
;TYPE:Gap fill
;WIDTH:0.277496
G1 F900
G1 X106.348 Y115.500 E0.29605
;LAYER_CHANGE
;Z:1.32
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;1.32


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X110.603 Y115.500 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z1.320 F9000.000
;AFTER_LAYER_CHANGE
;1.32
G1 X106.141 Y115.171
G1 E6.50000 F2400.000
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X124.859 Y115.171 E0.51757
G1 X124.859 Y115.829 E0.01822
G1 X106.141 Y115.829 E0.51757
G1 X106.141 Y115.231 E0.01656
G1 X105.725 Y114.755 F9000.000
;TYPE:External perimeter
G1 F900
G1 X125.275 Y114.755 E0.54056
G1 X125.275 Y116.245 E0.04120
G1 X105.725 Y116.245 E0.54056
G1 X105.725 Y114.815 E0.03954
G1 X106.125 Y114.765 F9000.000
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X109.980 Y114.802 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 X124.652 Y115.500 F9000.000
G1 E6.50000 F2400.000
;TYPE:Gap fill
;WIDTH:0.277496
G1 F900
G1 X106.348 Y115.500 E0.29605
;LAYER_CHANGE
;Z:1.48
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;1.48


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X110.603 Y115.500 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z1.480 F9000.000
;AFTER_LAYER_CHANGE
;1.48
G1 X106.141 Y115.199
G1 E6.50000 F2400.000
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X124.859 Y115.199 E0.51757
G1 X124.859 Y115.801 E0.01666
G1 X106.141 Y115.801 E0.51757
G1 X106.141 Y115.259 E0.01500
G1 X105.725 Y114.783 F9000.000
;TYPE:External perimeter
G1 F900
G1 X125.275 Y114.783 E0.54056
G1 X125.275 Y116.217 E0.03965
G1 X105.725 Y116.217 E0.54056
G1 X105.725 Y114.843 E0.03799
G1 X106.125 Y114.793 F9000.000
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X109.980 Y114.830 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 X124.652 Y115.500 F9000.000
G1 E6.50000 F2400.000
;TYPE:Gap fill
;WIDTH:0.22128
G1 F900
G1 X106.348 Y115.500 E0.22761
;LAYER_CHANGE
;Z:1.64
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;1.64


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X110.603 Y115.500 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z1.640 F9000.000
;AFTER_LAYER_CHANGE
;1.64
G1 X106.141 Y115.359
G1 E6.50000 F2400.000
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X124.859 Y115.359 E0.51757
G1 X124.859 Y115.641 E0.00781
G1 X106.141 Y115.641 E0.51757
G1 X106.141 Y115.419 E0.00616
G1 X105.725 Y114.943 F9000.000
;TYPE:External perimeter
G1 F900
G1 X125.275 Y114.943 E0.54056
G1 X125.275 Y116.057 E0.03080
G1 X105.725 Y116.057 E0.54056
G1 X105.725 Y115.003 E0.02914
G1 X106.125 Y114.951 F9000.000
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;1.8


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X109.980 Y114.990 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z1.800 F9000.000
;AFTER_LAYER_CHANGE
;1.8
G1 X105.725 Y115.103
G1 E6.50000 F2400.000
G1 F900
G1 X125.275 Y115.103 E0.54056
G1 X125.275 Y115.897 E0.02195
G1 X105.725 Y115.897 E0.54056
G1 X105.725 Y115.163 E0.02029
G1 X106.125 Y115.108 F9000.000
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X109.980 Y115.150 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 X125.067 Y115.500 F9000.000
G1 E6.50000 F2400.000
;TYPE:Gap fill
;WIDTH:0.412606
G1 F900
G1 X105.933 Y115.500 E0.48147
;LAYER_CHANGE
;Z:1.96
;HEIGHT:0.16
;BEFORE_LAYER_CHANGE
G92 E0
;1.96


G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X110.187 Y115.500 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 Z1.960 F9000.000
;AFTER_LAYER_CHANGE
;1.96
G1 X105.725 Y115.263
G1 E6.50000 F2400.000
;TYPE:External perimeter
;WIDTH:0.45
G1 F900
G1 X125.275 Y115.263 E0.54056
G1 X125.275 Y115.737 E0.01310
G1 X105.725 Y115.737 E0.54056
G1 X105.725 Y115.323 E0.01145
G1 X106.125 Y115.266 F9000.000
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000
G1 X109.980 Y115.310 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
G1 X125.067 Y115.500 F9000.000
G1 E6.50000 F2400.000
;TYPE:Gap fill
;WIDTH:0.0926063
G1 F900
G1 X105.933 Y115.500 E0.07417
G1 E-4.55000 F3300.000
;WIPE_START
G1 F7200.000;_WIPE
G1 X110.187 Y115.500 E-1.85250
;WIPE_END
G1 E-0.09750 F3300.000
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G1 Z3.96 F600 ; Move print head up
G1 X5 Y170 F9000 ; present print
G1 Z71.96 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84 X Y E ; disable motors
; filament used [mm] = 35.92
; filament used [cm3] = 0.09
; filament used [g] = 0.11
; filament cost = 0.00
; total filament used [g] = 0.11
; total filament cost = 0.00
; estimated printing time (normal mode) = 2m 14s

; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 3x3,228x3,228x228,3x228
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_model=~/(ENDER|CR).*/ and nozzle_diameter[0]==0.4";printer_notes=~/.*PRINTER_VENDOR_CREALITY.*/
; complete_objects = 1
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "Generic PLA @CREALITY"
; default_print_profile = 0.16mm OPTIMAL @CREALITY
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.1
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600{endif} ; Move print head up\nG1 X5 Y170 F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600{endif} ; Move print head further up\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84 X Y E ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 25
; extruder_clearance_radius = 45
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #DDDDDD
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA @CREALITY - Copy"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 10%
; fill_pattern = grid
; first_layer_acceleration = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; gap_fill_speed = 30
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 50
; inherits_cummulative = ;"Generic PLA @CREALITY";"Creality Ender-3"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.16
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.28
; max_print_height = 250
; max_print_speed = 100
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.08
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 40
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.16mm OPTIMAL @CREALITY
; printer_model = ENDER3
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_CREALITY\nPRINTER_MODEL_ENDER3\nPRINTER_HAS_BOWDEN
; printer_settings_id = Creality Ender-3 Custom
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 6.5
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 55
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 2
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 40
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 ; home all\nG1 Z2 F240\nG1 X2 Y10 F3000\nG1 Z0.28 F240\nG92 E0\nG1 Y190 E15 F1500 ; intro line\nG1 X2.3 F5000\nG92 E0\nG1 Y10 E15 F1200 ; intro line\nG92 E0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.15
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_synchronize_layers = 0
; support_material_threshold = 45
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 190
; template_custom_gcode = 
; thin_walls = 0
; threads = 4
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 30
; top_solid_layers = 7
; top_solid_min_thickness = 0
; travel_speed = 150
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
